const houses = [
    {
      id: '1',
      title: 'PAINTING',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/painting8.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/painting2.jpg'),
        require('../assets/painting3.jpg'),
        require('../assets/painting4.jpg'),
        require('../assets/painting5.jpg'),
        require('../assets/painting6.jpg'),
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'), 
        require('../assets/p3.jpg'),
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'SCULPTURE',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'), 
        require('../assets/p3.jpg'),
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'TEXTILES',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'PHOTOGRAPHY',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'DRAWING',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'PAPER',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'PRINT',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'DIGITAL',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/p4.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
  ];
  
  export default houses;