const houses = [
    {
      id: '1',
      title: 'PAINTING',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/painting8.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/painting2.jpg'),
        require('../assets/painting3.jpg'),
        require('../assets/painting4.jpg'),
        require('../assets/painting5.jpg'),
        require('../assets/painting6.jpg'),
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'), 
        require('../assets/p3.jpg'),
        require('../assets/p1.jpg'),
        require('../assets/p2.jpg'),
        require('../assets/p3.jpg'),
      ],
    },
    {
      id: '1',
      title: 'SCULPTURE',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/s6.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/s1.jpg'),
        require('../assets/s2.jpg'), 
        require('../assets/s3.jpg'),
        require('../assets/s4.jpg'),
        require('../assets/s5.jpg'),
        require('../assets/s6.jpg'),
        require('../assets/s7.jpg'),
        require('../assets/s8.jpg'),
        require('../assets/s9.jpg'),
        require('../assets/sculpture.png'),
        require('../assets/sculpture1.jpg'),
        require('../assets/sculpture2.jpg'),
        require('../assets/sculpture3.jpg'),
        require('../assets/sculpture4.jpg'),
        require('../assets/sculpture5.jpg'),
        require('../assets/sculpture6.jpg'),
      ],
    },
    {
      id: '1',
      title: 'TEXTILES',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/textile2.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/textile1.jpg'),
        require('../assets/textile3.jpg'),
        require('../assets/textile4.jpg'),
        require('../assets/textile5.jpg'),
        require('../assets/textile6.jpeg'),
        require('../assets/textile7.jpeg'),
        require('../assets/textile2.jpg'),
      ],
    },
    {
      id: '1',
      title: 'PHOTOGRAPHY',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/photo5.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/photo1.jpg'),
        require('../assets/photo4.jpg'),
        require('../assets/photo6.jpg'),
        require('../assets/photo2.jpg'),
        require('../assets/photo7.jpg'),
        require('../assets/photo8.jpg'),
        require('../assets/photo3.jpg'),
        require('../assets/photo5.jpg'),
        require('../assets/photo9.jpg'),
      ],
    },
    {
      id: '1',
      title: 'DRAWING',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/draw1.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/draw6.jpg'),
        require('../assets/draw2.jpg'),
        require('../assets/draw3.jpg'),
        require('../assets/draw4.jpg'),
        require('../assets/draw5.jpg'),
        require('../assets/draw1.jpg'),
      ],
    },
    {
      id: '1',
      title: 'PAPER WORK',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/w6.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/w1.jpeg'),
        require('../assets/w2.jpg'),
        require('../assets/w3.jpg'),
        require('../assets/w4.jpg'),
        require('../assets/w5.jpg'),
        require('../assets/w6.jpg'),
        require('../assets/w7.jpg'),
        require('../assets/w8.jpg'),
        require('../assets/w9.jpg'),
        require('../assets/w10.jpg'),
        require('../assets/w11.jpg'),
        require('../assets/w12.jpg'),
      ],
    },
    {
      id: '1',
      title: 'PRINT',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/pr5.jpg'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/pr1.jpg'),
        require('../assets/pr2.jpg'),
        require('../assets/pr3.jpg'),
        require('../assets/pr4.jpg'),
        require('../assets/pr6.jpg'),
        require('../assets/pr7.jpg'),
        require('../assets/pr8.jpg'),
        require('../assets/pr9.jpg'),
        require('../assets/pr10.jpg'),
        require('../assets/pr11.jpg'),
        require('../assets/pr12.jpg'),
        require('../assets/pr5.jpg'),
        require('../assets/pr13.jpg'),
        
      ],
    },
    {
      id: '1',
      title: 'DIGITAL',
      location: 'East Side Cedar Cottage Toronto',
      image: require('../assets/dig6.png'),
      details: `This building is located in the Oliver area, withing walking distance of shops...`,
      interiors: [
        require('../assets/dig1.jpg'),
        require('../assets/dig2.jpg'),
        require('../assets/dig3.jpg'),
        require('../assets/dig4.jpg'),
        require('../assets/dig5.jpg'),
        require('../assets/dig6.png'),
      ],
    },
  ];
  
  export default houses;